name: Docker CI/CD Pipeline

on:
  push:
    branches:
      - main  # Main branch'ine push yapıldığında tetiklenir
  pull_request:
    branches:
      - main  # Pull request geldiğinde de tetiklenebilir

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Docker'ı kur
      - name: Docker'ı kur
        uses: docker/setup-buildx-action@v2

      # 2. Docker imajını çek
      - name: Docker imajını çek
        run: docker pull ayseknd/alistirma:testinium.v2

      # 3. Docker container'ını çalıştır
      - name: Docker container'ını çalıştır
        run: |
          docker run --name alistirma-container -d ayseknd/alistirma:testinium.v2
          docker ps  # Çalışan container'ları listele

      # 4. Container içinde test komutu çalıştır
      - name: Container'ı test et
        run: |
          docker exec alistirma-container echo "Container çalışıyor!"  # Container içinde komut çalıştır
          docker logs alistirma-container  # Container loglarını görüntüle

      # 5. Docker container'ını durdur
      - name: Docker container'ını durdur
        run: docker stop alistirma-container

      # 6. Docker container'ını sil
      - name: Docker container'ını sil
        run: docker rm alistirma-container
